version: '3.5'

x-log: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"   # максимальный размер одного файла
      max-file: "10"    # максимальное колличество файлов

services:
  app:
    build: .
    restart: ${RESTART_POLICY:-always}
    container_name: app-${COMPOSE_PROJECT_NAME:-dash}
    ports:
      - 8055:8055
    <<: *logging
    volumes:
      - ./app:/usr/src/app/
